### PR TITLE
Formats napoleon docstrings in Python

### LINKED ISSUE #98: Properly format Google and Numpy (napoleon) docstrings in Python
Currently Google docstrings are inserted into the rendered rst directly, instead of being parsed by Sphinx's napoleon extension.
Sphinx implements napoleon via autodoc events. Part of fixing this issue might be to make changes to napoleon to make it easier to use outside of autodoc, though I'm pretty sure we should be able to use (https://github.com/sphinx-doc/sphinx/blob/6fa0262802a09050e09445c9fd630c69b5ad1204/sphinx/ext/napoleon/__init__.py#L326), or at least mimic it seeing as it's protected.

### PR DESCRIPTION
**Pull request by AWhetter**
Fixes #98

### CODE REVIEW

**Comment by AWhetter** [comment]
Rebased on to top of #121 to fix the tests and make this easier to review. Only the last commit is different from #121.

**Comment by agjohnson** [comment]
Unblocked. Will need a rebase

**Comment by AWhetter** [comment]
This should be easy enough. I'll have a go at this tomorrow.

**Comment by ericholscher** [comment]
:+1: -- once we have a few tests, I'll do a new release and push it up to pypi.

**Comment by AWhetter** [comment]
This should be good to go!

**Comment by ericholscher** [comment]
🎆

**Comment by ericholscher** [comment]
Thanks for your wonderful work here @AWhetter!

**Comment by ericholscher** [comment]
Just released 0.5.0. 🎆

**Pull request merged**
